[colors.bright]
black = "#7a8181"
blue = "#5ca7e4"
cyan = "#00c990"
green = "#49d0c5"
magenta = "#697098"
red = "#f76e6e"
white = "#989fb1"
yellow = "#dac26b"

[colors.cursor]
cursor = "#403f53"
text = "#989fb2"

[colors.normal]
black = "#011627"
blue = "#4876d6"
cyan = "#08916a"
green = "#2aa298"
magenta = "#403f53"
red = "#d3423e"
white = "#7a8181"
yellow = "#daaa01"

[colors.primary]
background = "#ffffff"
foreground = "#403f53"

[colors.selection]
background = "#f2f2f2"
text = "#403f53"

[font]
size = 8.0

[font.bold]
family = "SauceCodeProNerdFont"

[font.bold_italic]
family = "SauceCodeProNerdFont"

[font.italic]
family = "SauceCodeProNerdFont"

[font.normal]
family = "SauceCodeProNerdFont"

[[keyboard.bindings]]
chars = "\u001B[65;6u"
key = "A"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[68;6u"
key = "D"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[69;6u"
key = "E"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[69;6u"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[71;6u"
key = "G"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[72;6u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[73;6u"
key = "I"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;6u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;6u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;6u"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[77;6u"
key = "M"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[79;6u"
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[80;6u"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[81;6u"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[82;6u"
key = "R"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[83;6u"
key = "S"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[84;6u"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[87;6u"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[88;6u"
key = "X"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[89;6u"
key = "Y"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[90;6u"
key = "Z"
mods = "Control|Shift"

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
opacity = 1.0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0
