require("barbecue").setup({
  attach_navic = true,
  create_autocmd = true,
  include_buftypes = { "" },
  exclude_filetypes = { "toggleterm" },
  truncation = {
    enabled = true,
    method = "keep_basename",
  },
  modifiers = {
    dirname = ":~:.",
    basename = "",
  },
  custom_section = function() return "" end,
  symbols = {
    modified = false,
    ellipsis = "…",
    separator = ">",
  },

  kinds = {
    File = "",
    Package = "",
    Module = "",
    Namespace = "",
    Macro = "",
    Class = "ﴯ",
    Constructor = "",
    Field = "",
    Property = "ﰠ",
    Method = "",
    Struct = "ﴯ",
    Event = "",
    Interface = "",
    Enum = "",
    EnumMember = "",
    Constant = "",
    Function = "",
    TypeParameter = "",
    Variable = "",
    Operator = "",
    Null = "N",
    Boolean = "",
    Number = "",
    String = "",
    Key = "",
    Array = "",
    Object = "",
  },
})
