local icons = {
  rounded_left_filled = '', rounded_right_filled = '',
  arrow_left_filled = '', arrow_right_filled = '',
  arrow_left = '', arrow_right = '', sep = '|',
  ghost = '',
  cosmic = ' ',
  star = '★',
  search = ' ',
  scorpio = '♏︎',
  rocket = '🚀',
  trace = '✎',
  debug = ' ',
  info = '',
  warn = '',
  error = '',
  --[[ info = '', ]]
  --[[ warn = '', ]]
  --[[ error = '', ]]
  hint = '',
  perf = ' ',
  note = '',
  branch = '',
  file = '',
  dotdotdot = '…',
  information = '',
  symlink = '',
  line_number = '',
  flame = ' ',
  check = ' ',
  file1 = '',
  file2 = '',
  clock = '',
  word = '',
  diff = { add = ' ', modified = ' ', remove = ' ', },

  git = { unstaged = '✗', staged = '✓', unmerged = '',
    renamed = '➜', untracked = '★', deleted = '', ignored = '◌', },

  folder = { arrow_open = '', arrow_closed = '',
    default = '', open = '', empty = '', empty_open = '',
    symlink = '', symlink_open = '', },

  kind_icons = { Text = '', Method = 'm', Function = '',
    Constructor = '', Field = '', Variable = '', Class = '',
    Interface = '', Module = '', Property = '', Unit = '',
    Value = '', Enum = '', Keyword = '', Snippet = '',
    Color = '', File = '', Reference = '', Folder = '',
    EnumMember = '', Constant = '', Struct = '', Event = '',
    Operator = '', TypeParameter = '', },

  unclassified = {
    File = "",
    Array = "",
    Object = "",
    Macro = "",
    Class = "",
    Field = "",
    Property = "",
    Method = "",
    Struct = "",
    Event = "",
    Interface = "",
    EnumMember = "",
    Constant = "",
    Function = "",
    TypeParameter = "",
    Variable = "",
    Operator = "",
    Null = "",
    Boolean = "",
    Number = "",
    String = "",
    Key = "",
  }
}

return icons
