local icons = {

  border= {
    rounded_left_filled = "",
    rounded_right_filled = "",
    arrow_left_filled = "",
    arrow_right_filled = "",
    arrow_left = "",
    arrow_right = "",
    sep = "|",
    long_sep = "│",
    corner = "└",
    bottom = "─",
  },


  left = "", right = "",

  ghost = "󰊠",
  vim = " ",
  star = "★",
  search = " ",
  symlink = "",
  symlink_arrow = "➛",
  bookmark = "",
  close = "󰅖",
  dot = "●",

  -- NOTE: level
  info = "", warn = "󰀪", error = "", hint = "",
  trace = "✎", note = "", debug = " ",
  flame = " ", test = "", perf = "󱫍 ",

  branch = "󰘬",
  dotdotdot = "…",
  information = "",
  line_number = "",
  check = " ",
  cross = "",

  empty_file = "",
  file = "",
  file1 = "",
  file2 = "",
  clock = "",
  word = "",

  diff = { add = " ", modified = " ", remove = " " },
  git = {
    unstaged = "✗", staged = "✓", unmerged = "",
    renamed = "➜", untracked = "★", deleted = "", ignored = "◌",
  },
  folder = {
    arrow_open = "", arrow_closed = "",
    default = "", open = "",
    empty = "", empty_open = "",
    symlink = "", symlink_open = "",
  },

  kind_icons = {
    Array = "󰅪", -- "",
    Boolean = "",
    Color = "",
    Class = "󰠱", -- "", " ",
    Constructor = "", -- "", " ",
    Constant = "󰏿", -- "", "", "",
    Event = "", -- "",
    Enum = "",
    EnumMember = "", -- "",
    Field = "", -- "", "", " ", "",
    Function = "󰊕", -- "", " ",
    File = "", -- "",
    Folder = "",
    Interface = "", -- "",
    Keyword = "", -- "", " ",
    Key = "", -- "", " ",
    Method = "𝑚",
    Module = "󰕳", -- " ",
    Macro = "",
    Namespace = "",
    Null = "N",
    Number = "󰎠", -- , "#",
    Object = "",
    Operator = "",
    Package = "",
    Property = " ", -- "ﰠ", "", "",
    Reference = "",
    Snippet = "", -- "", "﬌ ",
    Struct = "", -- "", " ",
    String = "",
    Text = "󰊄", -- "",
    TypeParameter = "", -- "", "",
    Variable = "", -- "", "", " ",
    Value = "V",
    Unit = "", -- " ",
  },
}

return icons
