local icons = {
  rounded_left_filled = "",
  rounded_right_filled = "",
  arrow_left_filled = "",
  arrow_right_filled = "",
  arrow_left = "",
  arrow_right = "",
  sep = "|",
  close = "󰅖",
  dot = "●",
  left = "",
  right = "",
  ghost = "󰊠",
  vim = " ",
  star = "★",
  search = " ",
  -- NOTE: level
  trace = "✎",
  debug = " ",
  info = "",
  warn = "󰀪",
  error = "",
  hint = "",
  perf = "󱫍 ",
  note = "",
  branch = "󰘬",
  dotdotdot = "…",
  information = "",
  symlink = "",
  line_number = "",
  flame = " ",
  check = " ",
  cross = "",

  file = "",
  file1 = "",
  file2 = "",
  clock = "",
  test = "",
  word = "",
  diff = { add = " ", modified = " ", remove = " " },

  -- NOTE: git
  git = {
    unstaged = "✗", staged = "✓", unmerged = "",
    renamed = "➜", untracked = "★", deleted = "", ignored = "◌",
  },

  folder = {
    arrow_open = "", arrow_closed = "",
    default = "", open = "",
    empty = "", empty_open = "",
    symlink = "", symlink_open = "",
  },

  kind_icons = {
    Array = "󰅪", -- "",
    Boolean = "",
    Color = "",
    Class = "󰠱", -- "", " ",
    Constructor = "", -- "", " ",
    Constant = "󰏿", -- "", "", "",
    Event = "", -- "",
    Enum = "",
    EnumMember = "", -- "",
    Field = "", -- "", "", " ", "",
    Function = "󰊕", -- "", " ",
    File = "", -- "",
    Folder = "",
    Interface = "", -- "ﰮ ", "",
    Keyword = "", -- "", " ",
    Key = "", -- "", " ",
    Method = "𝑚", -- Method = "", "ƒ ",
    Module = "󰕳", -- " ",
    Macro = "",
    Namespace = "",
    Null = "N",
    Number = "󰎠", -- , "#",
    Object = "",
    Operator = "", -- "",
    Package = "",
    Property = " ", -- "ﰠ", "", "",
    Reference = "",
    Snippet = "", -- "", "﬌ ",
    Struct = "", -- "", " ",
    String = "",
    Text = "󰊄", -- "",
    TypeParameter = "", -- "", "",
    Variable = "", -- "", "", " ",
    Value = "V",
    Unit = "", -- " ",
  },
}

return icons
